"""
MUSE Event Types
"""

class EventTypes:
    """Core event types for the MUSE platform"""
    
    # User events
    USER_LIKED_POST = "USER_LIKED_POST"
    USER_SAVED_LOOK = "USER_SAVED_LOOK"
    USER_REJECTED_LOOK = "USER_REJECTED_LOOK"
    USER_VIEWED_PRODUCT = "USER_VIEWED_PRODUCT"
    USER_SEARCHED_STYLE = "USER_SEARCHED_STYLE"
    USER_ADDED_CLOTHING = "USER_ADDED_CLOTHING"
    USER_WORE_OUTFIT = "USER_WORE_OUTFIT"
    USER_COMPLETED_QUIZ = "USER_COMPLETED_QUIZ"
    USER_DISCOVERED_STYLE = "USER_DISCOVERED_STYLE"
    USER_FOLLOWED_CREATOR = "USER_FOLLOWED_CREATOR"
    USER_VIEWED_TREND = "USER_VIEWED_TREND"
    USER_PURCHASED_PRODUCT = "USER_PURCHASED_PRODUCT"
    
    # Style events
    STYLE_CREATED = "STYLE_CREATED"
    STYLE_UPDATED = "STYLE_UPDATED"
    STYLE_DISCOVERED = "STYLE_DISCOVERED"
    
    # Trend events
    TREND_DETECTED = "TREND_DETECTED"
    TREND_SCORE_UPDATED = "TREND_SCORE_UPDATED"
    TREND_PHASE_CHANGED = "TREND_PHASE_CHANGED"
    
    # Recommendation events
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    RECOMMENDATION_CLICKED = "RECOMMENDATION_CLICKED"
    RECOMMENDATION_REJECTED = "RECOMMENDATION_REJECTED"
    
    # All event types
    ALL = [
        # User events
        USER_LIKED_POST,
        USER_SAVED_LOOK,
        USER_REJECTED_LOOK,
        USER_VIEWED_PRODUCT,
        USER_SEARCHED_STYLE,
        USER_ADDED_CLOTHING,
        USER_WORE_OUTFIT,
        USER_COMPLETED_QUIZ,
        USER_DISCOVERED_STYLE,
        USER_FOLLOWED_CREATOR,
        USER_VIEWED_TREND,
        USER_PURCHASED_PRODUCT,
        # Style events
        STYLE_CREATED,
        STYLE_UPDATED,
        STYLE_DISCOVERED,
        # Trend events
        TREND_DETECTED,
        TREND_SCORE_UPDATED,
        TREND_PHASE_CHANGED,
        # Recommendation events
        RECOMMENDATION_GENERATED,
        RECOMMENDATION_CLICKED,
        RECOMMENDATION_REJECTED
    ]
